import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const OPENAI_KEY = Deno.env.get("OPENAI_API_KEY");
const OPENAI_MODEL = Deno.env.get("OPENAI_FAST_MODEL") || Deno.env.get("OPENAI_MODEL") || "gpt-5.6-sol";
const GEMINI_KEY = Deno.env.get("GEMINI_API_KEY");
const GEMINI_MODEL = Deno.env.get("GEMINI_MODEL") || "gemini-3.6-flash";
const headers = { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, apikey, content-type" };
function extractOutput(json: any) { if (typeof json?.output_text === "string") return json.output_text.trim(); return (Array.isArray(json?.output) ? json.output : []).flatMap((item: any) => Array.isArray(item?.content) ? item.content : []).filter((part: any) => part?.type === "output_text").map((part: any) => String(part.text || "")).join("").trim(); }
async function openAi(task: string, input: string) { if (!OPENAI_KEY) return null; const r = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${OPENAI_KEY}`, "content-type": "application/json" }, body: JSON.stringify({ model: OPENAI_MODEL, instructions: "نفّذ المهمة بدقة. لا تضف مقدمات أو اعتذارات أو Markdown إلا إذا كان النص الأصلي يتطلب ذلك.", input: `${task}\n\n${input}`, max_output_tokens: 1200 }) }); if (!r.ok) throw new Error(`OPENAI_${r.status}`); return extractOutput(await r.json()); }
async function gemini(task: string, input: string) { if (!GEMINI_KEY) return null; const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_KEY}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contents: [{ parts: [{ text: `${task}\n\n${input}` }] }], generationConfig: { temperature: 0.2, maxOutputTokens: 700 } }) }); if (!r.ok) throw new Error(`GEMINI_${r.status}`); const j = await r.json(); return String(j?.candidates?.[0]?.content?.parts?.[0]?.text || "").trim(); }
Deno.serve(async (req: Request) => { if (req.method === "OPTIONS") return new Response("ok", { headers }); if (req.method !== "POST") return new Response(JSON.stringify({ error: "METHOD_NOT_ALLOWED" }), { status: 405, headers }); try { const { text, locale = "ar", mode = "translate" } = await req.json(); const input = String(text || "").trim().slice(0, 6000); if (!input) return new Response(JSON.stringify({ error: "TEXT_REQUIRED" }), { status: 400, headers }); if (!OPENAI_KEY && !GEMINI_KEY) return new Response(JSON.stringify({ error: "AI_NOT_CONFIGURED" }), { status: 503, headers }); const task = mode === "summary" ? `لخّص النص التالي في ثلاث نقاط قصيرة باللغة ${locale}. حافظ على المعنى ولا تخترع معلومات.` : `ترجم النص التالي ترجمة طبيعية وواضحة إلى اللغة ${locale}. حافظ على الأسماء والأرقام والمعنى.`; let output = "", provider = "openai"; try { output = await openAi(task, input) || ""; } catch { provider = "gemini-fallback"; output = await gemini(task, input) || ""; } return new Response(JSON.stringify({ output, provider, model: provider === "openai" ? OPENAI_MODEL : GEMINI_MODEL }), { headers }); } catch (e) { return new Response(JSON.stringify({ error: "BAD_REQUEST", message: String(e).slice(0, 300) }), { status: 400, headers }); } });
