import { Ionicons } from '@expo/vector-icons';
import { useEffect,useMemo,useState } from 'react';
import { FlatList,Image,Pressable,StyleSheet,Text,View } from 'react-native';
import { supabase } from '../cloud/client';
import { ListingCard } from '../components/ListingCard';
import { useAteekTheme } from '../theme/ThemeProvider';
import { Listing,TabId } from '../types';

type Reel={id:string;caption:string;thumbnail_url?:string|null;created_at:string};
type FeedItem={kind:'listing';ts:number;listing:Listing}|{kind:'reel';ts:number;reel:Reel};
type Props={listings:Listing[];favorites:string[];onFavorite:(id:string)=>void;onOpen:(item:Listing)=>void;onNavigate:(tab:TabId)=>void;notificationCount:number;unreadChats:number;activeListings:number;profile?:Record<string,any>|null};
export function HomeScreen({listings,favorites,onFavorite,onOpen,onNavigate,notificationCount,unreadChats,activeListings,profile}:Props){
  const{colors,lowData}=useAteekTheme();const[reels,setReels]=useState<Reel[]>([]),[reelCount,setReelCount]=useState(0);
  useEffect(()=>{let alive=true;void Promise.all([supabase.from('reels').select('id,caption,thumbnail_url,created_at').eq('status','active').order('created_at',{ascending:false}).limit(3),supabase.from('reels').select('id',{count:'exact',head:true}).eq('status','active')]).then(([r,c])=>{if(!alive)return;if(!r.error)setReels((r.data??[]) as Reel[]);setReelCount(c.count??0)}).catch(()=>{});const ch=supabase.channel('home-reels-count').on('postgres_changes',{event:'*',schema:'public',table:'reels'},()=>{void supabase.from('reels').select('id',{count:'exact',head:true}).eq('status','active').then(({count})=>alive&&setReelCount(count??0))}).subscribe();return()=>{alive=false;void supabase.removeChannel(ch)}},[]);
  const latest=useMemo(()=>{const a:FeedItem[]=[...listings.slice().sort((x,y)=>y.createdAt-x.createdAt).slice(0,5).map(x=>({kind:'listing' as const,ts:x.createdAt,listing:x})),...reels.map(x=>({kind:'reel' as const,ts:Date.parse(x.created_at),reel:x}))];return a.sort((x,y)=>y.ts-x.ts)},[listings,reels]);
  const quick=[{label:'ريلز',value:reelCount,icon:'play-circle-outline' as const,tab:'ai' as TabId},{label:'الإعلانات',value:activeListings,icon:'grid-outline' as const,tab:'profile' as TabId},{label:'بحث AI',value:null,icon:'sparkles-outline' as const,tab:'search' as TabId},{label:'المحادثات',value:unreadChats,icon:'chatbubble-ellipses-outline' as const,tab:'chats' as TabId}];
  return <FlatList data={latest} keyExtractor={(x)=>x.kind==='listing'?`l-${x.listing.id}`:`r-${x.reel.id}`} numColumns={2} initialNumToRender={lowData?4:8} maxToRenderPerBatch={lowData?4:8} windowSize={lowData?3:6} columnWrapperStyle={s.row} contentContainerStyle={s.content} ListHeaderComponent={<View style={s.headerWrap}><View style={s.top}><View><Text style={[s.brand,{color:colors.gold}]}>ATEEK</Text><Text style={[s.subtitle,{color:colors.muted}]}>Command Center</Text></View><View style={s.topActions}><Pressable accessibilityLabel="الإشعارات" onPress={()=>onNavigate('notifications')} style={[s.iconBtn,{backgroundColor:colors.glassStrong,borderColor:colors.line}]}><Ionicons name="notifications-outline" size={24} color={colors.ink}/>{notificationCount>0&&<View style={[s.badge,{backgroundColor:colors.danger}]}><Text style={s.badgeText}>{Math.min(notificationCount,99)}</Text></View>}</Pressable><Pressable accessibilityLabel="الحساب" onPress={()=>onNavigate('profile')} style={[s.avatar,{backgroundColor:colors.glassStrong,borderColor:colors.line}]}>{profile?.avatar_url?<Image source={{uri:String(profile.avatar_url)}} style={StyleSheet.absoluteFill}/>:<Ionicons name="person" size={22} color={colors.gold}/>}</Pressable></View></View><View style={s.quickGrid}>{quick.map(q=><Pressable key={q.label} onPress={()=>onNavigate(q.tab)} style={[s.quick,{backgroundColor:colors.glass,borderColor:colors.line}]}><Ionicons name={q.icon} size={24} color={colors.gold}/><Text style={[s.quickLabel,{color:colors.ink}]}>{q.label}</Text>{q.value!=null&&<Text style={[s.quickValue,{color:colors.cyan}]}>{q.value}</Text>}</Pressable>)}</View><View style={s.section}><Text style={[s.sectionTitle,{color:colors.ink}]}>الخلاصة الذكية</Text><Text style={[s.sectionNote,{color:colors.muted}]}>آخر 5 إعلانات + آخر 3 ريلز</Text></View></View>} ListEmptyComponent={<View style={[s.empty,{backgroundColor:colors.glass,borderColor:colors.line}]}><Ionicons name="cube-outline" size={44} color={colors.muted}/><Text style={[s.emptyTitle,{color:colors.ink}]}>لا توجد عناصر بعد</Text></View>} renderItem={({item})=>item.kind==='listing'?<ListingCard item={item.listing} favorite={favorites.includes(item.listing.id)} onFavorite={()=>onFavorite(item.listing.id)} onPress={()=>onOpen(item.listing)}/>:<Pressable onPress={()=>onNavigate('ai')} style={[s.reelCard,{backgroundColor:colors.glassStrong,borderColor:colors.line}]}>{item.reel.thumbnail_url?<Image source={{uri:item.reel.thumbnail_url}} style={s.reelImage}/>:<View style={[s.reelImage,s.reelFallback]}><Ionicons name="play" size={34} color={colors.gold}/></View>}<View style={s.reelCopy}><Ionicons name="play-circle" size={18} color={colors.cyan}/><Text numberOfLines={2} style={[s.reelText,{color:colors.ink}]}>{item.reel.caption||'ريل جديد'}</Text></View></Pressable>}/>;
}
const s=StyleSheet.create({content:{paddingBottom:26},headerWrap:{padding:16,gap:16},top:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:28,fontWeight:'900',letterSpacing:1.1},subtitle:{fontSize:11,textAlign:'right'},topActions:{flexDirection:'row-reverse',gap:10},iconBtn:{width:46,height:46,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},avatar:{width:46,height:46,borderRadius:23,borderWidth:1,alignItems:'center',justifyContent:'center',overflow:'hidden'},badge:{position:'absolute',top:-4,left:-4,minWidth:20,height:20,borderRadius:10,alignItems:'center',justifyContent:'center',paddingHorizontal:4},badgeText:{color:'#fff',fontSize:9,fontWeight:'900'},quickGrid:{flexDirection:'row-reverse',flexWrap:'wrap',gap:8},quick:{width:'48%',minHeight:92,borderRadius:20,borderWidth:1,padding:14,justifyContent:'space-between'},quickLabel:{fontWeight:'900',textAlign:'right'},quickValue:{fontSize:20,fontWeight:'900',textAlign:'right'},section:{marginTop:8},sectionTitle:{fontSize:19,fontWeight:'900',textAlign:'right'},sectionNote:{fontSize:10,textAlign:'right',marginTop:3},row:{paddingHorizontal:16,justifyContent:'space-between'},reelCard:{width:'48%',borderRadius:20,borderWidth:1,overflow:'hidden',marginBottom:12},reelImage:{width:'100%',height:152},reelFallback:{alignItems:'center',justifyContent:'center'},reelCopy:{padding:10,flexDirection:'row-reverse',gap:6,alignItems:'center'},reelText:{flex:1,fontSize:11,fontWeight:'800',textAlign:'right'},empty:{marginHorizontal:16,borderRadius:22,padding:28,alignItems:'center',borderWidth:1},emptyTitle:{fontSize:16,fontWeight:'900',marginTop:10}});
