import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { formatPrice } from '../data/seed';
import { colors } from '../theme/colors';
import { parsePrice } from '../utils/money';
import { Listing } from '../types';

export function ListingDetails({ item, visible, favorite, onClose, onFavorite, onOffer, onChat }: { item: Listing | null; visible: boolean; favorite: boolean; onClose: () => void; onFavorite: () => void; onOffer: (amount: number) => void; onChat: () => void }) {
  const [offer, setOffer] = useState(''); if (!item) return null;
  const submit = () => { const value = parsePrice(offer); if (!value) return Alert.alert('أدخل سعرًا صحيحًا'); onOffer(value); setOffer(''); Alert.alert('أُضيفت مسودة العرض', 'محفوظة محليًا فقط. لم تُرسل للبائع؛ تجدها في حسابي ← عروضي.'); };
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.root}><ScrollView showsVerticalScrollIndicator={false}><View style={styles.imageWrap}><Image source={{ uri: item.image }} style={styles.image} /><Pressable style={[styles.floating, styles.close]} onPress={onClose}><Ionicons name="close" size={23} color={colors.ink} /></Pressable><Pressable style={[styles.floating, styles.fav]} onPress={onFavorite}><Ionicons name={favorite ? 'heart' : 'heart-outline'} size={22} color={favorite ? colors.danger : colors.ink} /></Pressable></View>
    <View style={styles.body}><View style={styles.badge}><Text style={styles.badgeText}>{item.condition}</Text></View><Text style={styles.title}>{item.title}</Text><Text style={styles.price}>{formatPrice(item.price)}</Text><View style={styles.meta}><Meta icon="time-outline" text={item.age} /><Meta icon="location-outline" text={item.location} /></View>
      <View style={styles.separator} /><Text style={styles.heading}>التفاصيل</Text><Text style={styles.description}>{item.description}</Text><View style={styles.seller}><Ionicons name="chevron-back" size={19} color={colors.muted} /><View style={styles.sellerInfo}><View><View style={styles.sellerName}><Text style={styles.sellerTitle}>{item.seller}</Text>{item.verified && <Ionicons name="checkmark-circle" size={16} color={colors.success} />}</View><Text style={styles.sellerSub}>لم يُتحقق من هوية البائع</Text></View><View style={styles.avatar}><Ionicons name="person" size={22} color={colors.gold} /></View></View></View>
      <Text style={styles.heading}>قدّم عرضك</Text><View style={styles.offerRow}><Pressable style={styles.offerButton} onPress={submit}><Text style={styles.offerButtonText}>حفظ العرض</Text></Pressable><TextInput value={offer} onChangeText={setOffer} placeholder="المبلغ بالدينار" placeholderTextColor={colors.muted} keyboardType="number-pad" style={styles.offerInput} /></View>
      <Pressable style={styles.chat} onPress={onChat}><Ionicons name="chatbubble-ellipses" size={20} color={colors.gold} /><Text style={styles.chatText}>مراسلة البائع</Text></Pressable>
    </View></ScrollView></View></Modal>;
}
function Meta({ icon, text }: { icon: keyof typeof Ionicons.glyphMap; text: string }) { return <View style={styles.metaItem}><Ionicons name={icon} size={16} color={colors.muted} /><Text style={styles.metaText}>{text}</Text></View>; }
const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.cream }, imageWrap: { height: 340, backgroundColor: colors.line }, image: { width: '100%', height: '100%' }, floating: { position: 'absolute', top: 45, width: 42, height: 42, borderRadius: 15, backgroundColor: 'rgba(255,255,255,.94)', alignItems: 'center', justifyContent: 'center' }, close: { right: 16 }, fav: { left: 16 },
  body: { padding: 20, alignItems: 'flex-end' }, badge: { backgroundColor: colors.goldSoft, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 5 }, badgeText: { color: colors.forest, fontSize: 10, fontWeight: '800' }, title: { fontSize: 24, fontWeight: '900', color: colors.ink, textAlign: 'right', marginTop: 9 }, price: { fontSize: 22, fontWeight: '900', color: colors.success, marginTop: 6 }, meta: { flexDirection: 'row-reverse', gap: 18, marginTop: 11 }, metaItem: { flexDirection: 'row-reverse', alignItems: 'center', gap: 4 }, metaText: { color: colors.muted, fontSize: 11 }, separator: { width: '100%', height: 1, backgroundColor: colors.line, marginVertical: 19 }, heading: { fontSize: 16, fontWeight: '900', color: colors.ink, marginBottom: 8 }, description: { color: colors.muted, fontSize: 13, lineHeight: 23, textAlign: 'right', writingDirection: 'rtl' },
  seller: { width: '100%', height: 78, backgroundColor: colors.paper, borderRadius: 18, borderWidth: 1, borderColor: colors.line, padding: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 20 }, sellerInfo: { flexDirection: 'row', gap: 10, alignItems: 'center' }, sellerName: { flexDirection: 'row-reverse', alignItems: 'center', gap: 4 }, sellerTitle: { fontWeight: '900', color: colors.ink, textAlign: 'right' }, sellerSub: { color: colors.muted, fontSize: 10, marginTop: 3 }, avatar: { width: 46, height: 46, borderRadius: 16, backgroundColor: colors.forest, alignItems: 'center', justifyContent: 'center' },
  offerRow: { flexDirection: 'row', gap: 8, width: '100%' }, offerInput: { flex: 1, height: 52, borderRadius: 15, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 13, textAlign: 'right', color: colors.ink }, offerButton: { height: 52, borderRadius: 15, backgroundColor: colors.gold, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' }, offerButtonText: { color: colors.forest, fontWeight: '900', fontSize: 12 }, chat: { width: '100%', height: 54, backgroundColor: colors.forest, borderRadius: 17, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', marginTop: 12 }, chatText: { color: colors.paper, fontWeight: '900' }
});
