import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Location from 'expo-location';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { EmptyState } from '../components/EmptyState';
import { ListingCard } from '../components/ListingCard';
import { categories } from '../data/seed';
import { colors } from '../theme/colors';
import { Listing } from '../types';

type Saved={q:string;category:string};
const HISTORY='ateek.search.history.v1', SAVED='ateek.search.saved.v1';
const distance=(a:number,b:number,c:number,d:number)=>{const r=6371,to=(x:number)=>x*Math.PI/180,dl=to(c-a),dn=to(d-b),h=Math.sin(dl/2)**2+Math.cos(to(a))*Math.cos(to(c))*Math.sin(dn/2)**2;return 2*r*Math.asin(Math.sqrt(h));};
export function SearchScreen({listings,favorites,onFavorite,onOpen,initialCategory='all'}:{listings:Listing[];favorites:string[];onFavorite:(id:string)=>void;onOpen:(item:Listing)=>void;initialCategory?:string}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState(initialCategory),[history,setHistory]=useState<string[]>([]),[saved,setSaved]=useState<Saved[]>([]),[near,setNear]=useState<{lat:number;lon:number}|null>(null);
 useEffect(()=>{void Promise.all([AsyncStorage.getItem(HISTORY),AsyncStorage.getItem(SAVED)]).then(([h,v])=>{if(h)setHistory(JSON.parse(h));if(v)setSaved(JSON.parse(v));}).catch(()=>{});},[]);
 const commitHistory=async(q:string)=>{const x=q.trim();if(x.length<2)return;const next=[x,...history.filter(v=>v!==x)].slice(0,8);setHistory(next);await AsyncStorage.setItem(HISTORY,JSON.stringify(next));};
 const saveSearch=async()=>{const x=query.trim();if(!x&&category==='all')return Alert.alert('البحث المحفوظ','اكتب كلمة أو اختر قسمًا أولًا.');const next=[{q:x,category},...saved.filter(v=>v.q!==x||v.category!==category)].slice(0,12);setSaved(next);await AsyncStorage.setItem(SAVED,JSON.stringify(next));Alert.alert('تم الحفظ','سيبقى هذا البحث محفوظًا على جهازك وتظهر مطابقاته الجديدة داخل شاشة البحث.');};
 const nearest=async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')return Alert.alert('الموقع','يمكنك تفعيل إذن الموقع لفرز الإعلانات التي أضاف أصحابها موقعًا جغرافيًا.');const x=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setNear({lat:x.coords.latitude,lon:x.coords.longitude});};
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('ar');const arr=listings.filter(x=>(category==='all'||x.category===category)&&(`${x.title} ${x.location} ${x.description}`.toLocaleLowerCase('ar').includes(q)));return near?[...arr].sort((x,y)=>{const dx=x.latitude!=null&&x.longitude!=null?distance(near.lat,near.lon,x.latitude,x.longitude):Infinity,dy=y.latitude!=null&&y.longitude!=null?distance(near.lat,near.lon,y.latitude,y.longitude):Infinity;return dx-dy;}):arr;},[listings,category,query,near]);
 const savedMatches=saved.reduce((n,s)=>n+listings.filter(x=>(s.category==='all'||x.category===s.category)&&`${x.title} ${x.description} ${x.location}`.toLocaleLowerCase('ar').includes(s.q.toLocaleLowerCase('ar'))).length,0);
 return <View style={styles.root}><View style={styles.header}><Text style={styles.title}>اكتشف بذكاء</Text><Text style={styles.subtitle}>بحث سريع • محفوظ • الأقرب إليك</Text><View style={styles.search}><Pressable accessibilityLabel="حفظ البحث الحالي" onPress={()=>void saveSearch()}><Ionicons name="bookmark-outline" size={21} color={colors.gold}/></Pressable><TextInput accessibilityLabel="حقل البحث" autoFocus value={query} onChangeText={setQuery} onSubmitEditing={()=>void commitHistory(query)} placeholder="ماذا تبحث عنه؟" placeholderTextColor={colors.muted} style={styles.input}/><Ionicons name="search" size={21} color={colors.muted}/></View><View style={styles.actions}><Pressable accessibilityLabel="فرز حسب الأقرب" style={styles.action} onPress={()=>void nearest()}><Ionicons name="navigate-outline" size={16} color={colors.cyan}/><Text style={styles.actionText}>{near?'الأقرب مفعّل':'الأقرب إليك'}</Text></Pressable><Text style={styles.alertText}>{saved.length?`${saved.length} بحث محفوظ • ${savedMatches} مطابقة`:'لا توجد عمليات بحث محفوظة'}</Text></View></View>
 {!!history.length&&<View style={styles.history}><Text style={styles.smallTitle}>بحثت مؤخرًا</Text><FlatList horizontal inverted data={history} keyExtractor={x=>x} showsHorizontalScrollIndicator={false} renderItem={({item})=><Pressable accessibilityLabel={`إعادة البحث عن ${item}`} onPress={()=>setQuery(item)} style={styles.historyChip}><Text style={styles.chipText}>{item}</Text></Pressable>}/></View>}
 <View style={styles.chips}><FlatList horizontal inverted showsHorizontalScrollIndicator={false} data={[{id:'all',label:'الكل'},...categories]} keyExtractor={x=>x.id} renderItem={({item})=><Pressable accessibilityLabel={`قسم ${item.label}`} onPress={()=>setCategory(item.id)} style={[styles.chip,category===item.id&&styles.chipActive]}><Text style={[styles.chipText,category===item.id&&styles.chipTextActive]}>{item.label}</Text></Pressable>}/></View>
 <FlatList data={filtered} keyExtractor={x=>x.id} numColumns={2} columnWrapperStyle={styles.row} contentContainerStyle={styles.results} ListEmptyComponent={<EmptyState icon="search-outline" title="لم نجد نتائج" body="جرّب كلمة أخرى أو اختر قسمًا مختلفًا"/>} renderItem={({item})=><ListingCard item={item} favorite={favorites.includes(item.id)} onFavorite={()=>onFavorite(item.id)} onPress={()=>{void commitHistory(query);onOpen(item);}}/>}/></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'transparent'},header:{backgroundColor:colors.glassStrong,padding:20,paddingTop:24,alignItems:'flex-end',borderBottomWidth:1,borderBottomColor:colors.line},title:{color:colors.ink,fontSize:27,fontWeight:'900'},subtitle:{color:colors.goldSoft,fontSize:12,marginTop:3},search:{marginTop:17,width:'100%',height:54,borderRadius:18,backgroundColor:colors.glass,flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:10,borderWidth:1,borderColor:colors.line},input:{flex:1,textAlign:'right',writingDirection:'rtl',color:colors.ink},actions:{width:'100%',marginTop:10,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between'},action:{flexDirection:'row-reverse',gap:6,alignItems:'center'},actionText:{color:colors.cyan,fontSize:11,fontWeight:'800'},alertText:{color:colors.muted,fontSize:10},history:{paddingHorizontal:14,paddingTop:10},smallTitle:{color:colors.muted,textAlign:'right',fontSize:10,marginBottom:7},historyChip:{paddingHorizontal:12,paddingVertical:7,borderRadius:999,backgroundColor:colors.glass,marginHorizontal:4},chips:{height:61,paddingVertical:11,paddingHorizontal:10},chip:{paddingHorizontal:16,height:38,justifyContent:'center',borderRadius:14,backgroundColor:colors.glass,borderWidth:1,borderColor:colors.line,marginHorizontal:4},chipActive:{backgroundColor:colors.gold,borderColor:colors.gold},chipText:{color:colors.muted,fontSize:12,fontWeight:'700'},chipTextActive:{color:colors.forest},results:{padding:16,paddingTop:4},row:{justifyContent:'space-between'}});
