import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';
import { useColorScheme } from 'react-native';

export type ThemeMode='dark'|'light'|'system';
export type Locale='ar'|'ku'|'en';
const dark={forest:'#090A0F',forestSoft:'#12151D',gold:'#E0B66C',goldSoft:'#D8C49A',cream:'#090A0F',paper:'#0F1219',ink:'#F6F8FB',muted:'#7E8798',line:'rgba(190,198,211,0.16)',danger:'#FF7B86',success:'#73F0CF',overlay:'rgba(5,6,10,0.88)',glass:'#10131A',glassStrong:'#151922',cyan:'#73F0CF',surface:'#090A0F'};
const light={forest:'#1B2029',forestSoft:'#EEF1F5',gold:'#A87528',goldSoft:'#F2E5CD',cream:'#F7F8FA',paper:'#FFFFFF',ink:'#171B22',muted:'#687282',line:'rgba(42,48,60,0.13)',danger:'#C74B57',success:'#218B70',overlay:'rgba(14,17,24,0.18)',glass:'#F2F4F7',glassStrong:'#FFFFFF',cyan:'#168F75',surface:'#F7F8FA'};
export type ThemeColors=typeof dark;
const strings:Record<Locale,Record<string,string>>={
  ar:{globalHub:'عتيك AI',globalSub:'تثمين • وصف • ذكاء فوري',close:'إغلاق',onlineNow:'متصل الآن',queued:'بالانتظار',language:'اللغة',aiSeller:'استوديو البيع الذكي',productTitle:'اسم المنتج',category:'الفئة',condition:'الحالة',fairPrice:'تثمين ذكي',autoDescription:'وصف تلقائي',analyzing:'جارٍ التحليل عبر Gemini…',resilience:'العمل دون اتصال',retryQueue:'إعادة إرسال العمليات المعلّقة',themeLight:'تفعيل الوضع الفاتح',themeDark:'تفعيل الوضع الداكن',lowDataOn:'إيقاف وضع البيانات المنخفضة',lowDataOff:'تشغيل وضع البيانات المنخفضة'},
  ku:{globalHub:'عەتیك AI',globalSub:'نرخاندن • وەسف • زیرەکی',close:'داخستن',onlineNow:'ئۆنلاین',queued:'چاوەڕوان',language:'زمان',aiSeller:'ستۆدیۆی فرۆشتنی زیرەک',productTitle:'ناوی بەرهەم',category:'پۆل',condition:'دۆخ',fairPrice:'نرخاندنی زیرەک',autoDescription:'وەسفی خۆکار',analyzing:'Gemini خەریکی شیکردنەوەیە…',resilience:'کارکردن بەبێ ئینتەرنێت',retryQueue:'ناردنەوەی کارە چاوەڕوانەکان',themeLight:'دۆخی ڕووناک',themeDark:'دۆخی تاریک',lowDataOn:'کوژاندنەوەی داتای کەم',lowDataOff:'چالاککردنی داتای کەم'},
  en:{globalHub:'ATEEK AI',globalSub:'pricing • copy • instant intelligence',close:'Close',onlineNow:'Online now',queued:'Queued',language:'Language',aiSeller:'AI Seller Studio',productTitle:'Product title',category:'Category',condition:'Condition',fairPrice:'Fair price',autoDescription:'Auto description',analyzing:'Analyzing with Gemini…',resilience:'Offline resilience',retryQueue:'Retry queued actions',themeLight:'Enable light mode',themeDark:'Enable dark mode',lowDataOn:'Disable low-data mode',lowDataOff:'Enable low-data mode'}
};
type Ctx={mode:ThemeMode;resolved:'dark'|'light';colors:ThemeColors;setMode:(m:ThemeMode)=>void;toggle:()=>void;lowData:boolean;setLowData:(v:boolean)=>void;locale:Locale;setLocale:(v:Locale)=>void;isRTL:boolean;dir:'rtl'|'ltr';t:(key:string)=>string};
const ThemeContext=createContext<Ctx>({mode:'dark',resolved:'dark',colors:dark,setMode:()=>{},toggle:()=>{},lowData:false,setLowData:()=>{},locale:'ar',setLocale:()=>{},isRTL:true,dir:'rtl',t:k=>k});
const THEME_KEY='ateek.theme.mode',LOW_DATA_KEY='ateek.low.data',LOCALE_KEY='ateek.locale';
export function ThemeProvider({children}:{children:PropsWithChildren['children']}){const system=useColorScheme();const[mode,setModeState]=useState<ThemeMode>('dark');const[lowData,setLowDataState]=useState(false);const[locale,setLocaleState]=useState<Locale>('ar');useEffect(()=>{void Promise.all([AsyncStorage.getItem(THEME_KEY),AsyncStorage.getItem(LOW_DATA_KEY),AsyncStorage.getItem(LOCALE_KEY)]).then(([m,l,lang])=>{if(m==='dark'||m==='light'||m==='system')setModeState(m);setLowDataState(l==='1');if(lang==='ar'||lang==='ku'||lang==='en')setLocaleState(lang)}).catch(()=>{})},[]);const setMode=(m:ThemeMode)=>{setModeState(m);void AsyncStorage.setItem(THEME_KEY,m)};const setLowData=(v:boolean)=>{setLowDataState(v);void AsyncStorage.setItem(LOW_DATA_KEY,v?'1':'0')};const setLocale=(v:Locale)=>{setLocaleState(v);void AsyncStorage.setItem(LOCALE_KEY,v)};const resolved=mode==='system'?(system==='light'?'light':'dark'):mode;const isRTL=locale!=='en';const value=useMemo<Ctx>(()=>({mode,resolved,colors:resolved==='dark'?dark:light,setMode,toggle:()=>setMode(resolved==='dark'?'light':'dark'),lowData,setLowData,locale,setLocale,isRTL,dir:isRTL?'rtl':'ltr',t:(key:string)=>strings[locale][key]??strings.en[key]??key}),[mode,resolved,lowData,locale,isRTL]);return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>}
export const useAteekTheme=()=>useContext(ThemeContext);
