import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';
import { useColorScheme } from 'react-native';

export type ThemeMode='dark'|'light'|'system';
export type Locale='ar'|'ku'|'en';
const dark={forest:'#07130F',forestSoft:'#0B2019',gold:'#F1B84B',goldSoft:'#F8E3B2',cream:'#000000',paper:'rgba(10,10,10,0.96)',ink:'#F8FAF9',muted:'#9AA39F',line:'rgba(255,255,255,0.12)',danger:'#FF6B6B',success:'#55D69E',overlay:'rgba(0,0,0,0.84)',glass:'rgba(20,28,25,0.78)',glassStrong:'rgba(7,12,10,0.95)',cyan:'#69E6C1',surface:'#050505'};
const light={forest:'#0D2D25',forestSoft:'#DCF7EC',gold:'#D89A21',goldSoft:'#FFF1C9',cream:'#FFFFFF',paper:'rgba(255,255,255,0.98)',ink:'#10231D',muted:'#66766F',line:'rgba(13,45,37,0.12)',danger:'#C94848',success:'#26845D',overlay:'rgba(13,45,37,0.22)',glass:'rgba(247,251,249,0.88)',glassStrong:'rgba(255,255,255,0.98)',cyan:'#1E9F7B',surface:'#FFFFFF'};
export type ThemeColors=typeof dark;
const strings:Record<Locale,Record<string,string>>={
  ar:{globalHub:'عتيك العالمي',globalSub:'الذكاء • الأداء • المرونة',close:'إغلاق',onlineNow:'متصل الآن',queued:'بالانتظار',language:'اللغة',aiSeller:'استوديو البيع الذكي',productTitle:'اسم المنتج',category:'الفئة',condition:'الحالة',fairPrice:'تثمين ذكي',autoDescription:'وصف تلقائي',analyzing:'جارٍ التحليل عبر Gemini…',resilience:'العمل دون اتصال',retryQueue:'إعادة إرسال العمليات المعلّقة',themeLight:'تفعيل الوضع الفاتح',themeDark:'تفعيل الوضع الداكن',lowDataOn:'إيقاف وضع البيانات المنخفضة',lowDataOff:'تشغيل وضع البيانات المنخفضة'},
  ku:{globalHub:'عەتیك جیهانی',globalSub:'زیرەکی • خێرایی • بەردەوامی',close:'داخستن',onlineNow:'ئۆنلاین',queued:'چاوەڕوان',language:'زمان',aiSeller:'ستۆدیۆی فرۆشتنی زیرەک',productTitle:'ناوی بەرهەم',category:'پۆل',condition:'دۆخ',fairPrice:'نرخاندنی زیرەک',autoDescription:'وەسفی خۆکار',analyzing:'Gemini خەریکی شیکردنەوەیە…',resilience:'کارکردن بەبێ ئینتەرنێت',retryQueue:'ناردنەوەی کارە چاوەڕوانەکان',themeLight:'دۆخی ڕووناک',themeDark:'دۆخی تاریک',lowDataOn:'کوژاندنەوەی داتای کەم',lowDataOff:'چالاککردنی داتای کەم'},
  en:{globalHub:'ATEEK Global',globalSub:'AI • performance • resilience',close:'Close',onlineNow:'Online now',queued:'Queued',language:'Language',aiSeller:'AI Seller Studio',productTitle:'Product title',category:'Category',condition:'Condition',fairPrice:'Fair price',autoDescription:'Auto description',analyzing:'Analyzing with Gemini…',resilience:'Offline resilience',retryQueue:'Retry queued actions',themeLight:'Enable light mode',themeDark:'Enable dark mode',lowDataOn:'Disable low-data mode',lowDataOff:'Enable low-data mode'}
};
type Ctx={mode:ThemeMode;resolved:'dark'|'light';colors:ThemeColors;setMode:(m:ThemeMode)=>void;toggle:()=>void;lowData:boolean;setLowData:(v:boolean)=>void;locale:Locale;setLocale:(v:Locale)=>void;isRTL:boolean;dir:'rtl'|'ltr';t:(key:string)=>string};
const ThemeContext=createContext<Ctx>({mode:'dark',resolved:'dark',colors:dark,setMode:()=>{},toggle:()=>{},lowData:false,setLowData:()=>{},locale:'ar',setLocale:()=>{},isRTL:true,dir:'rtl',t:k=>k});
const THEME_KEY='ateek.theme.mode',LOW_DATA_KEY='ateek.low.data',LOCALE_KEY='ateek.locale';
export function ThemeProvider({children}:{children:PropsWithChildren['children']}){const system=useColorScheme();const[mode,setModeState]=useState<ThemeMode>('dark');const[lowData,setLowDataState]=useState(false);const[locale,setLocaleState]=useState<Locale>('ar');useEffect(()=>{void Promise.all([AsyncStorage.getItem(THEME_KEY),AsyncStorage.getItem(LOW_DATA_KEY),AsyncStorage.getItem(LOCALE_KEY)]).then(([m,l,lang])=>{if(m==='dark'||m==='light'||m==='system')setModeState(m);setLowDataState(l==='1');if(lang==='ar'||lang==='ku'||lang==='en')setLocaleState(lang)}).catch(()=>{})},[]);const setMode=(m:ThemeMode)=>{setModeState(m);void AsyncStorage.setItem(THEME_KEY,m)};const setLowData=(v:boolean)=>{setLowDataState(v);void AsyncStorage.setItem(LOW_DATA_KEY,v?'1':'0')};const setLocale=(v:Locale)=>{setLocaleState(v);void AsyncStorage.setItem(LOCALE_KEY,v)};const resolved=mode==='system'?(system==='light'?'light':'dark'):mode;const isRTL=locale!=='en';const value=useMemo<Ctx>(()=>({mode,resolved,colors:resolved==='dark'?dark:light,setMode,toggle:()=>setMode(resolved==='dark'?'light':'dark'),lowData,setLowData,locale,setLocale,isRTL,dir:isRTL?'rtl':'ltr',t:(key:string)=>strings[locale][key]??strings.en[key]??key}),[mode,resolved,lowData,locale,isRTL]);return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>}
export const useAteekTheme=()=>useContext(ThemeContext);
