import { Ionicons } from '@expo/vector-icons';
import { useRef } from 'react';
import { Animated,Pressable,StyleSheet,Text,View } from 'react-native';
import { useAteekTheme } from '../theme/ThemeProvider';
import { TabId } from '../types';
const tabs:{id:TabId;label:string;icon:keyof typeof Ionicons.glyphMap}[]=[{id:'home',label:'الرئيسية',icon:'home-outline'},{id:'add',label:'الإضافة',icon:'add-circle-outline'},{id:'notifications',label:'الإشعارات',icon:'notifications-outline'},{id:'chats',label:'المحادثات',icon:'chatbubble-ellipses-outline'},{id:'profile',label:'الحساب',icon:'person-outline'}];
function NavItem({tab,selected,onPress}:{tab:(typeof tabs)[number];selected:boolean;onPress:()=>void}){const{colors,animationsEnabled}=useAteekTheme();const s=useRef(new Animated.Value(1)).current;const press=()=>{if(animationsEnabled)Animated.sequence([Animated.spring(s,{toValue:.86,useNativeDriver:true,speed:45,bounciness:3}),Animated.spring(s,{toValue:1,useNativeDriver:true,speed:30,bounciness:8})]).start();onPress()};return <Pressable accessibilityRole="button" accessibilityState={{selected}} accessibilityLabel={tab.label} style={styles.tab} onPress={press}><Animated.View style={{transform:[{scale:s}]}}><Ionicons name={selected?(tab.icon as string).replace('-outline','') as keyof typeof Ionicons.glyphMap:tab.icon} size={24} color={selected?colors.gold:colors.muted}/></Animated.View><Text numberOfLines={1} style={[styles.label,{color:selected?colors.gold:colors.muted},selected&&styles.selected]}>{tab.label}</Text></Pressable>}
export function BottomNav({active,onChange}:{active:TabId;onChange:(tab:TabId)=>void}){const{colors}=useAteekTheme();return <View style={[styles.bar,{backgroundColor:colors.glassStrong,borderTopColor:colors.line}]}>{tabs.map(tab=><NavItem key={tab.id} tab={tab} selected={active===tab.id} onPress={()=>onChange(tab.id)}/>)}</View>}
const styles=StyleSheet.create({bar:{height:76,borderTopWidth:1,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-around',paddingBottom:6},tab:{flex:1,minWidth:0,alignItems:'center',justifyContent:'center',gap:4},label:{fontSize:9,fontWeight:'700'},selected:{fontWeight:'900'}});
