import { useEffect,useRef,useState } from 'react';
import { Alert,Image,Pressable,Share,StyleSheet,Text,TextInput,View } from 'react-native';
import { captureRef } from 'react-native-view-shot';
import { supabase } from '../cloud/client';
import { Listing } from '../types';
import { formatPrice } from '../data/seed';
import { colors } from '../theme/colors';

export function useRealDailyView(id:string,refresh:()=>Promise<unknown>){useEffect(()=>{void supabase.rpc('ateek_listing_view',{p_listing_id:id}).then(({error})=>{if(!error)void refresh();});},[id,refresh]);}
export function OwnerListingTools({item,refresh}:{item:Listing;refresh:()=>Promise<unknown>}){const [price,setPrice]=useState(String(item.price)),[busy,setBusy]=useState(false);const run=async(fn:()=>PromiseLike<any>)=>{if(busy)return;setBusy(true);try{const r=await fn();if((r as any)?.error)throw (r as any).error;await refresh();}catch(e:any){Alert.alert('تعذّر التنفيذ',e.message||'حاول مجددًا');}finally{setBusy(false)}};return <View style={s.owner}><Text style={s.h}>أدوات البائع السريعة</Text><TextInput accessibilityLabel="السعر الجديد" keyboardType="number-pad" value={price} onChangeText={setPrice} placeholderTextColor={colors.muted} style={s.input}/><Pressable accessibilityRole="button" accessibilityLabel="حفظ السعر الجديد" style={s.btn} onPress={()=>void run(()=>supabase.rpc('ateek_listing_price',{p_listing_id:item.id,p_price:Number(price)}))}><Text style={s.bt}>حفظ السعر</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="نسخ الإعلان كإعلان جديد" style={s.alt} onPress={()=>Alert.alert('نسخ الإعلان؟','سينشأ إعلان جديد بنفس البيانات والصورة.',[{text:'إلغاء'},{text:'نسخ',onPress:()=>void run(()=>supabase.rpc('ateek_listing_duplicate',{p_listing_id:item.id}))}])}><Text style={s.at}>نسخ الإعلان كجديد</Text></Pressable></View>}
export function SimilarListings({item,listings,onOpen}:{item:Listing;listings:Listing[];onOpen:(x:Listing)=>void}){const xs=listings.filter(x=>x.id!==item.id&&x.status==='active'&&(x.category===item.category||x.location===item.location)).sort((a,b)=>(a.category===item.category?-1:0)-(b.category===item.category?-1:0)).slice(0,4);if(!xs.length)return null;return <View style={s.sim}><Text style={s.h}>إعلانات مشابهة</Text>{xs.map(x=><Pressable accessibilityRole="button" accessibilityLabel={`فتح إعلان مشابه ${x.title}`} key={x.id} onPress={()=>onOpen(x)} style={s.simRow}><Image source={{uri:x.image}} style={s.thumb}/><View style={{flex:1}}><Text numberOfLines={1} style={s.t}>{x.title}</Text><Text style={s.p}>{formatPrice(x.price)}</Text></View></Pressable>)}</View>}
export function ShareListingCard({item}:{item:Listing}){const ref=useRef<View>(null),[busy,setBusy]=useState(false);const share=async()=>{if(!ref.current||busy)return;setBusy(true);try{const uri=await captureRef(ref,{format:'png',quality:.92,result:'tmpfile'});await Share.share({title:'عتيك',message:`${item.title} — ${formatPrice(item.price)}\nعبر تطبيق عتيك`,url:uri});}catch(e:any){Alert.alert('تعذّرت المشاركة',e.message||'حاول مجددًا');}finally{setBusy(false)}};return <><View ref={ref} collapsable={false} style={s.shareCard}><Image source={{uri:item.image}} style={s.shareImage}/><View style={s.shareBody}><Text style={s.logo}>عتيك • ATEEK</Text><Text numberOfLines={2} style={s.shareTitle}>{item.title}</Text><Text style={s.sharePrice}>{formatPrice(item.price)}</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel="مشاركة بطاقة الإعلان كصورة" onPress={()=>void share()} style={s.btn}><Text style={s.bt}>{busy?'جارٍ تجهيز البطاقة…':'مشاركة بطاقة الإعلان'}</Text></Pressable></>}
const s=StyleSheet.create({owner:{gap:9,backgroundColor:colors.glass,borderRadius:20,padding:14,borderWidth:1,borderColor:colors.line},h:{color:colors.ink,fontSize:16,fontWeight:'900',textAlign:'right'},input:{height:48,borderRadius:14,borderWidth:1,borderColor:colors.line,color:colors.ink,textAlign:'right',paddingHorizontal:12,backgroundColor:colors.glassStrong},btn:{minHeight:46,borderRadius:14,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center'},bt:{color:colors.forest,fontWeight:'900'},alt:{minHeight:46,borderRadius:14,borderWidth:1,borderColor:colors.gold,alignItems:'center',justifyContent:'center'},at:{color:colors.gold,fontWeight:'800'},sim:{gap:9},simRow:{flexDirection:'row-reverse',gap:10,alignItems:'center',backgroundColor:colors.glass,borderRadius:16,padding:9,borderWidth:1,borderColor:colors.line},thumb:{width:58,height:58,borderRadius:12},t:{color:colors.ink,fontWeight:'800',textAlign:'right'},p:{color:colors.gold,fontWeight:'900',textAlign:'right',marginTop:4},shareCard:{height:310,borderRadius:24,overflow:'hidden',backgroundColor:'#0B1F1A'},shareImage:{width:'100%',height:205},shareBody:{padding:14},logo:{color:colors.gold,fontWeight:'900',textAlign:'right'},shareTitle:{color:'#fff',fontSize:18,fontWeight:'900',textAlign:'right',marginTop:4},sharePrice:{color:colors.gold,fontSize:20,fontWeight:'900',textAlign:'right',marginTop:5}});
