import { Ionicons } from '@expo/vector-icons';
import { useEffect,useState } from 'react';
import { Image,Pressable,StyleSheet,Text,View } from 'react-native';
import Animated,{useAnimatedStyle,useSharedValue,withSpring} from 'react-native-reanimated';
import { supabase } from '../cloud/client';
import { formatPrice } from '../data/seed';
import { openSpatialProfile } from '../social/spatialSocialBus';
import { haptics } from '../system/haptics';
import { shadows } from '../theme/colors';
import { useAteekTheme } from '../theme/ThemeProvider';
import { Listing } from '../types';
type Props={item:Listing;favorite:boolean;onFavorite:()=>void;onPress:()=>void};
type Metrics={verified:boolean;completedDeals:number;activeSeller:boolean;newAccount:boolean;accountAgeDays:number};
const cache=new Map<string,Metrics>();
export function ListingCard({item,favorite,onFavorite,onPress}:Props){
 const{colors,lowData}=useAteekTheme();const[loaded,setLoaded]=useState(false),[metrics,setMetrics]=useState<Metrics|null>(item.sellerId?cache.get(item.sellerId)??null:null);const press=useSharedValue(1),tilt=useSharedValue(0);const motion=useAnimatedStyle(()=>({transform:[{perspective:900},{scale:press.value},{rotateX:`${tilt.value}deg`},{rotateY:`${-tilt.value*.7}deg`}]}));
 useEffect(()=>{let alive=true;if(!item.sellerId||cache.has(item.sellerId))return;void supabase.rpc('ateek_seller_metrics',{p_seller:item.sellerId}).then(({data,error})=>{if(!alive||error||!data)return;const m=data as Metrics;cache.set(item.sellerId!,m);setMetrics(m)});return()=>{alive=false}},[item.sellerId]);
 const down=()=>{haptics.tap();press.value=withSpring(.965,{damping:14,stiffness:260});tilt.value=withSpring(1.2,{damping:14,stiffness:220})};const up=()=>{press.value=withSpring(1,{damping:13,stiffness:240});tilt.value=withSpring(0,{damping:13,stiffness:220})};
 return <Animated.View style={[styles.wrap,motion]}><Pressable accessibilityRole="button" accessibilityLabel={`${item.title}، ${formatPrice(item.price)}، ${item.location}`} onPressIn={down} onPressOut={up} onPress={onPress} style={[styles.card,{backgroundColor:'#0F1219',borderColor:'rgba(188,197,211,.18)'}]}><View style={[styles.edge,{backgroundColor:'rgba(255,255,255,.035)'}]}/><View style={[styles.imageWrap,{backgroundColor:'#151922'}]}>{!loaded&&<View style={[StyleSheet.absoluteFill,{backgroundColor:'#161B23'}]}/>}<Image accessibilityLabel={`صورة ${item.title}`} source={{uri:item.image}} resizeMode="cover" progressiveRenderingEnabled fadeDuration={lowData?0:180} onLoadEnd={()=>setLoaded(true)} style={[styles.image,{opacity:loaded?1:0}]}/><View pointerEvents="none" style={styles.imageShade}/><Pressable accessibilityRole="button" accessibilityLabel={favorite?'إزالة من المفضلة':'إضافة إلى المفضلة'} style={styles.favorite} onPress={()=>{haptics.medium();onFavorite()}} hitSlop={8}><Ionicons name={favorite?'heart':'heart-outline'} size={20} color={favorite?colors.danger:'#F5F7FA'}/></Pressable>{metrics?.verified&&<View style={styles.verified}><Ionicons name="shield-checkmark" size={13} color="#73F0CF"/></View>}{item.sellerId&&<Pressable accessibilityRole="button" accessibilityLabel="فتح بروفايل البائع" onPress={()=>{haptics.light();openSpatialProfile(item.sellerId)}} style={styles.profileButton}><Ionicons name="person" size={14} color="#E7EBF1"/></Pressable>}</View><View style={styles.body}><Text style={styles.title} numberOfLines={1}>{item.title}</Text><Text style={styles.price}>{formatPrice(item.price)}</Text>{metrics&&(metrics.activeSeller||metrics.completedDeals>0||metrics.newAccount)&&<View style={styles.trustRow}>{metrics.activeSeller&&<Text style={[styles.trust,{color:'#73F0CF'}]}>● بائع نشط</Text>}{metrics.completedDeals>0&&<Text style={[styles.trust,{color:'#8FC8FF'}]}>{metrics.completedDeals} صفقة</Text>}{metrics.newAccount&&<Text style={[styles.trust,{color:'#E0B66C'}]}>حساب جديد</Text>}</View>}<View style={styles.meta}><View style={styles.metaItem}><Ionicons name="location-outline" size={13} color="#73F0CF"/><Text style={styles.metaText}>{item.location}</Text></View><Text style={styles.dot}>•</Text><Text style={styles.metaText}>{item.age}</Text></View></View></Pressable></Animated.View>}
const styles=StyleSheet.create({wrap:{width:'48.3%',marginBottom:14},card:{width:'100%',borderRadius:24,overflow:'hidden',borderWidth:1,...shadows.card},edge:{position:'absolute',left:0,right:0,top:0,height:1,zIndex:4},imageWrap:{height:154,overflow:'hidden'},image:{width:'100%',height:'100%'},imageShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(3,5,8,.08)'},favorite:{position:'absolute',top:9,left:9,width:38,height:38,borderRadius:14,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(255,255,255,.16)',backgroundColor:'rgba(10,12,18,.88)'},verified:{position:'absolute',top:9,right:9,width:30,height:30,borderRadius:12,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(115,240,207,.36)',backgroundColor:'rgba(10,20,20,.9)'},profileButton:{position:'absolute',right:9,bottom:9,width:34,height:34,borderRadius:13,borderWidth:1,borderColor:'rgba(255,255,255,.15)',backgroundColor:'rgba(10,12,18,.88)',alignItems:'center',justifyContent:'center'},body:{padding:12,alignItems:'flex-end'},title:{fontSize:14,fontWeight:'900',writingDirection:'rtl',width:'100%',textAlign:'right',color:'#F6F8FB'},price:{fontSize:16,fontWeight:'900',marginTop:6,color:'#E0B66C'},trustRow:{width:'100%',flexDirection:'row-reverse',flexWrap:'wrap',gap:7,marginTop:7},trust:{fontSize:9,fontWeight:'900'},meta:{flexDirection:'row-reverse',alignItems:'center',marginTop:7,width:'100%'},metaItem:{flexDirection:'row-reverse',alignItems:'center',gap:2},metaText:{fontSize:10,color:'#7E8798'},dot:{marginHorizontal:5,color:'#7E8798'}});
