import { Ionicons } from '@expo/vector-icons';
import { useEffect,useRef,useState } from 'react';
import { Animated,Image,Pressable,StyleSheet,Text,View } from 'react-native';
import { formatPrice } from '../data/seed';
import { shadows } from '../theme/colors';
import { useAteekTheme } from '../theme/ThemeProvider';
import { Listing } from '../types';
type Props={item:Listing;favorite:boolean;onFavorite:()=>void;onPress:()=>void};
export function ListingCard({item,favorite,onFavorite,onPress}:Props){const{colors,lowData}=useAteekTheme();const[loaded,setLoaded]=useState(false);const glow=useRef(new Animated.Value(.25)).current;useEffect(()=>{if(loaded)return;const l=Animated.loop(Animated.sequence([Animated.timing(glow,{toValue:.7,duration:900,useNativeDriver:true}),Animated.timing(glow,{toValue:.25,duration:900,useNativeDriver:true})]));l.start();return()=>l.stop()},[loaded,glow]);return <Pressable accessibilityRole="button" accessibilityLabel={`${item.title}، ${formatPrice(item.price)}، ${item.location}`} style={({pressed})=>[styles.card,{backgroundColor:colors.glass,borderColor:colors.line},pressed&&styles.pressed]} onPress={onPress}><View style={[styles.imageWrap,{backgroundColor:colors.forestSoft}]}>{!loaded&&<Animated.View pointerEvents="none" style={[StyleSheet.absoluteFill,{opacity:glow,backgroundColor:colors.cyan}]}/>}<Image accessibilityLabel={`صورة ${item.title}`} source={{uri:item.image}} resizeMode="cover" progressiveRenderingEnabled fadeDuration={lowData?0:180} onLoadEnd={()=>setLoaded(true)} style={[styles.image,{opacity:loaded?1:0}]}/><Pressable accessibilityRole="button" accessibilityLabel={favorite?'إزالة من المفضلة':'إضافة إلى المفضلة'} style={[styles.favorite,{backgroundColor:colors.glassStrong,borderColor:colors.line}]} onPress={onFavorite} hitSlop={8}><Ionicons name={favorite?'heart':'heart-outline'} size={20} color={favorite?colors.danger:colors.ink}/></Pressable></View><View style={styles.body}><Text style={[styles.title,{color:colors.ink}]} numberOfLines={1}>{item.title}</Text><Text style={[styles.price,{color:colors.gold}]}>{formatPrice(item.price)}</Text><View style={styles.meta}><View style={styles.metaItem}><Ionicons name="location-outline" size={13} color={colors.cyan}/><Text style={[styles.metaText,{color:colors.muted}]}>{item.location}</Text></View><Text style={[styles.dot,{color:colors.muted}]}>•</Text><Text style={[styles.metaText,{color:colors.muted}]}>{item.age}</Text></View></View></Pressable>}
const styles=StyleSheet.create({card:{width:'48.3%',borderRadius:22,overflow:'hidden',marginBottom:14,borderWidth:1,...shadows.card},pressed:{opacity:.9,transform:[{scale:.975}]},imageWrap:{height:148,overflow:'hidden'},image:{width:'100%',height:'100%'},favorite:{position:'absolute',top:9,left:9,width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center',borderWidth:1},body:{padding:12,alignItems:'flex-end'},title:{fontSize:14,fontWeight:'900',writingDirection:'rtl',width:'100%',textAlign:'right'},price:{fontSize:16,fontWeight:'900',marginTop:6},meta:{flexDirection:'row-reverse',alignItems:'center',marginTop:7,width:'100%'},metaItem:{flexDirection:'row-reverse',alignItems:'center',gap:2},metaText:{fontSize:10},dot:{marginHorizontal:5}});
