import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,StyleSheet,Text,View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '../cloud/client';
import { useAteekTheme } from '../theme/ThemeProvider';

type Metrics={verified:boolean;completedDeals:number;activeSeller:boolean;newAccount:boolean;accountAgeDays:number};
export function SellerTrustPanel({sellerId,onMessage}:{sellerId?:string;onMessage?:()=>void}){const{colors}=useAteekTheme();const[m,setM]=useState<Metrics|null>(null);const[error,setError]=useState(false);useEffect(()=>{let alive=true;if(!sellerId)return;void supabase.rpc('ateek_seller_metrics',{p_seller:sellerId}).then(({data,error})=>{if(!alive)return;if(error){setError(true);return}setM(data as Metrics)});return()=>{alive=false}},[sellerId]);if(!sellerId)return null;if(!m&&!error)return <ActivityIndicator accessibilityLabel="تحميل معلومات البائع" color={colors.gold}/>;if(error)return null;return <View style={[s.card,{backgroundColor:colors.glass,borderColor:colors.line}]}><View style={s.row}>{m?.verified&&<View style={[s.badge,{borderColor:colors.cyan}]}><Ionicons name="shield-checkmark" size={15} color={colors.cyan}/><Text style={[s.badgeText,{color:colors.cyan}]}>حساب موثّق</Text></View>}{m?.activeSeller&&<View style={[s.badge,{borderColor:colors.success}]}><Ionicons name="flash" size={15} color={colors.success}/><Text style={[s.badgeText,{color:colors.success}]}>بائع نشط</Text></View>}</View><View style={s.stats}><View style={s.stat}><Text style={[s.num,{color:colors.gold}]}>{m?.completedDeals??0}</Text><Text style={[s.label,{color:colors.muted}]}>صفقة مكتملة</Text></View><View style={s.stat}><Text style={[s.num,{color:colors.ink}]}>{m?.accountAgeDays??0}</Text><Text style={[s.label,{color:colors.muted}]}>يوم بالحساب</Text></View></View>{m?.newAccount&&<View style={[s.warning,{borderColor:colors.gold}]}><Ionicons name="warning-outline" size={17} color={colors.gold}/><Text style={[s.warningText,{color:colors.ink}]}>حساب جديد بلا صفقات مكتملة بعد. افحص السلعة ولا تدفع قبل المعاينة.</Text></View>}{onMessage&&<Pressable accessibilityRole="button" accessibilityLabel="مراسلة البائع" onPress={onMessage} style={[s.message,{backgroundColor:colors.gold}]}><Ionicons name="chatbubble-ellipses" size={18} color={colors.forest}/><Text style={[s.messageText,{color:colors.forest}]}>مراسلة البائع</Text></Pressable>}</View>}
const s=StyleSheet.create({card:{borderRadius:22,borderWidth:1,padding:14,gap:12},row:{flexDirection:'row-reverse',gap:8,flexWrap:'wrap'},badge:{flexDirection:'row-reverse',alignItems:'center',gap:5,borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:6},badgeText:{fontSize:11,fontWeight:'900'},stats:{flexDirection:'row-reverse',gap:10},stat:{flex:1,alignItems:'center',padding:12,borderRadius:16,backgroundColor:'rgba(255,255,255,.035)'},num:{fontSize:24,fontWeight:'900'},label:{fontSize:10,marginTop:2},warning:{flexDirection:'row-reverse',gap:8,borderWidth:1,borderRadius:15,padding:10,alignItems:'center'},warningText:{flex:1,fontSize:11,lineHeight:18,textAlign:'right'},message:{minHeight:48,borderRadius:16,alignItems:'center',justifyContent:'center',flexDirection:'row-reverse',gap:8},messageText:{fontWeight:'900'}});
