import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,StyleSheet,Text,View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { supabase } from '../cloud/client';
import { useLocale } from '../i18n/LocaleProvider';
import { useAteekTheme } from '../theme/ThemeProvider';

type Metrics={verified:boolean;completedDeals:number;activeSeller:boolean;newAccount:boolean;accountAgeDays:number};
export function SellerTrustPanel({sellerId,onMessage}:{sellerId?:string;onMessage?:()=>void}){const{colors}=useAteekTheme();const{t,formatNumber,isRTL}=useLocale();const[m,setM]=useState<Metrics|null>(null);const[error,setError]=useState(false);const[resolvedSellerId,setResolvedSellerId]=useState<string|null>(null);useEffect(()=>{let alive=true;setM(null);setError(false);setResolvedSellerId(null);if(!sellerId)return()=>{alive=false};void Promise.resolve(supabase.rpc('ateek_seller_metrics',{p_seller:sellerId}).then(({data,error})=>{if(!alive)return;if(error){setError(true);setResolvedSellerId(sellerId);return}setError(false);setM(data as Metrics);setResolvedSellerId(sellerId)})).catch(()=>{if(!alive)return;setError(true);setResolvedSellerId(sellerId)});return()=>{alive=false}},[sellerId]);if(!sellerId)return null;if(resolvedSellerId!==sellerId)return <ActivityIndicator accessibilityRole="progressbar" accessibilityState={{busy:true}} accessibilityLabel={t('sellerTrust.loading')} color={colors.gold}/>;if(error)return null;const flow=isRTL?'row-reverse':'row';const textAlign=isRTL?'right':'left';return <View style={[s.card,{backgroundColor:colors.glass,borderColor:colors.line}]}><View style={[s.row,{flexDirection:flow}]}>{m?.verified&&<View style={[s.badge,{borderColor:colors.cyan,flexDirection:flow}]}><Ionicons accessible={false} name="shield-checkmark" size={15} color={colors.cyan}/><Text style={[s.badgeText,{color:colors.cyan}]}>{t('sellerTrust.verified')}</Text></View>}{m?.activeSeller&&<View style={[s.badge,{borderColor:colors.success,flexDirection:flow}]}><Ionicons accessible={false} name="flash" size={15} color={colors.success}/><Text style={[s.badgeText,{color:colors.success}]}>{t('sellerTrust.active')}</Text></View>}</View><View style={[s.stats,{flexDirection:flow}]}><View style={s.stat}><Text style={[s.num,{color:colors.gold}]}>{formatNumber(m?.completedDeals??0)}</Text><Text style={[s.label,{color:colors.muted}]}>{t('sellerTrust.completedDeals')}</Text></View><View style={s.stat}><Text style={[s.num,{color:colors.ink}]}>{formatNumber(m?.accountAgeDays??0)}</Text><Text style={[s.label,{color:colors.muted}]}>{t('sellerTrust.accountAgeDays')}</Text></View></View>{m?.newAccount&&<View accessibilityRole="alert" style={[s.warning,{borderColor:colors.gold,flexDirection:flow}]}><Ionicons accessible={false} name="warning-outline" size={17} color={colors.gold}/><Text style={[s.warningText,{color:colors.ink,textAlign}]}>{t('sellerTrust.newAccountWarning')}</Text></View>}{onMessage&&<Pressable accessibilityRole="button" accessibilityLabel={t('sellerTrust.message')} hitSlop={8} onPress={onMessage} style={[s.message,{backgroundColor:colors.gold,flexDirection:flow}]}><Ionicons accessible={false} name="chatbubble-ellipses" size={18} color={colors.forest}/><Text style={[s.messageText,{color:colors.forest}]}>{t('sellerTrust.message')}</Text></Pressable>}</View>}
const s=StyleSheet.create({card:{borderRadius:22,borderWidth:1,padding:14,gap:12},row:{gap:8,flexWrap:'wrap'},badge:{alignItems:'center',gap:5,borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:6},badgeText:{fontSize:11,fontWeight:'900'},stats:{gap:10},stat:{flex:1,alignItems:'center',padding:12,borderRadius:16,backgroundColor:'rgba(255,255,255,.035)'},num:{fontSize:24,fontWeight:'900'},label:{fontSize:10,marginTop:2},warning:{gap:8,borderWidth:1,borderRadius:15,padding:10,alignItems:'center'},warningText:{flex:1,fontSize:11,lineHeight:18},message:{minHeight:48,borderRadius:16,alignItems:'center',justifyContent:'center',gap:8},messageText:{fontWeight:'900'}});
