import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const OPENAI_KEY = Deno.env.get("OPENAI_API_KEY");
const OPENAI_MODEL = Deno.env.get("OPENAI_VISION_MODEL") || Deno.env.get("OPENAI_MODEL") || "gpt-5.6-sol";
const GEMINI_KEY = Deno.env.get("GEMINI_API_KEY");
const GEMINI_MODEL = Deno.env.get("GEMINI_MODEL") || "gemini-3.6-flash";
const headers = { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, apikey, content-type" };
function extractOutput(json: any) { if (typeof json?.output_text === "string") return json.output_text.trim(); return (Array.isArray(json?.output) ? json.output : []).flatMap((item: any) => Array.isArray(item?.content) ? item.content : []).filter((part: any) => part?.type === "output_text").map((part: any) => String(part.text || "")).join("").trim(); }
function parseObject(raw: string) { const stripped = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim(); try { return JSON.parse(stripped); } catch { return {}; } }
function normalize(parsed: any, categories: any[]) { const allowed = new Set(categories.map((x: any) => String(x?.id)).filter(Boolean)); const category = allowed.has(String(parsed?.category)) ? String(parsed.category) : null; const price = Number(parsed?.estimated_price); return { category, title: String(parsed?.title || "").trim().slice(0, 120), description: String(parsed?.description || "").trim().slice(0, 700), estimated_price: Number.isFinite(price) && price > 0 ? Math.round(price) : null, confidence: Math.max(0, Math.min(1, Number(parsed?.confidence) || 0)), caveat: String(parsed?.caveat || "السعر تقديري ويحتاج مراجعة السوق والحالة الفعلية.").slice(0, 240) }; }
async function openAi(prompt: string, mimeType: string, b64: string) { if (!OPENAI_KEY) return null; const r = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${OPENAI_KEY}`, "content-type": "application/json" }, body: JSON.stringify({ model: OPENAI_MODEL, instructions: "أنت محلل صور لسلع سوق عتيك العراقي. لا تدّعِ الأصالة أو الماركة أو الحالة إذا لم تكن ظاهرة. أعد JSON صالحاً فقط دون Markdown.", input: [{ role: "user", content: [{ type: "input_text", text: prompt }, { type: "input_image", image_url: `data:${mimeType};base64,${b64}` }] }], max_output_tokens: 900 }) }); if (!r.ok) throw new Error(`OPENAI_${r.status}`); return extractOutput(await r.json()); }
async function gemini(prompt: string, mimeType: string, b64: string) { if (!GEMINI_KEY) return null; const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_KEY}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }, { inlineData: { mimeType, data: b64 } }] }], generationConfig: { responseMimeType: "application/json", temperature: 0.2, maxOutputTokens: 550 } }) }); if (!r.ok) throw new Error(`GEMINI_${r.status}`); const j = await r.json(); return String(j?.candidates?.[0]?.content?.parts?.[0]?.text || "{}"); }
Deno.serve(async (req: Request) => { if (req.method === "OPTIONS") return new Response("ok", { headers }); if (req.method !== "POST") return new Response(JSON.stringify({ error: "METHOD_NOT_ALLOWED" }), { status: 405, headers }); try { const { imageBase64, mimeType = "image/jpeg", categories = [] } = await req.json(); const b64 = String(imageBase64 || ""); const mime = String(mimeType || "image/jpeg"); if (!/^image\/(jpeg|png|webp)$/i.test(mime)) return new Response(JSON.stringify({ error: "UNSUPPORTED_IMAGE_TYPE" }), { status: 400, headers }); if (b64.length < 100 || b64.length > 12_000_000) return new Response(JSON.stringify({ error: "IMAGE_REQUIRED_OR_TOO_LARGE" }), { status: 400, headers }); if (!OPENAI_KEY && !GEMINI_KEY) return new Response(JSON.stringify({ error: "AI_NOT_CONFIGURED" }), { status: 503, headers }); const safeCategories = Array.isArray(categories) ? categories.slice(0, 30) : []; const prompt = `حلل صورة سلعة في سوق عراقي. أعد JSON فقط بالشكل {"category":"id","title":"عنوان عربي قصير","description":"وصف واقعي مختصر","estimated_price":12345,"confidence":0.0,"caveat":"..."}. اختر category حصراً من هذه القائمة: ${JSON.stringify(safeCategories)}. السعر بالدينار العراقي وهو تقدير تقريبي فقط. لا تخترع ماركة أو عمر أو حالة أو أصالة غير ظاهرة.`; let raw = "{}", provider = "openai"; try { raw = await openAi(prompt, mime, b64) || "{}"; } catch { provider = "gemini-fallback"; raw = await gemini(prompt, mime, b64) || "{}"; } const result = normalize(parseObject(raw), safeCategories); return new Response(JSON.stringify({ ...result, provider, model: provider === "openai" ? OPENAI_MODEL : GEMINI_MODEL }), { headers }); } catch (e) { return new Response(JSON.stringify({ error: "BAD_REQUEST", message: String(e).slice(0, 300) }), { status: 400, headers }); } });
