import React,{useRef,useState} from 'react';
import { Animated,Dimensions,Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import OnlineApp from './cloud/OnlineApp';
import { DynamicBackground } from './components/DynamicBackground';
import { colors } from './theme/colors';
import { ThemeProvider,useAteekTheme } from './theme/ThemeProvider';
import { BUILD_INFO } from './config/buildInfo';
type State={failed:boolean};
class AppErrorBoundary extends React.Component<React.PropsWithChildren,State>{state:State={failed:false};static getDerivedStateFromError():State{return{failed:true}}componentDidCatch(error:unknown){console.error('ATEEK UI error',error)}reset=()=>this.setState({failed:false});render(){if(!this.state.failed)return this.props.children;return <SafeAreaView style={styles.root}><View style={styles.card}><Text style={styles.brand}>ATEEK • عتيك</Text><Text style={styles.title}>حدث خطأ غير متوقع في الواجهة</Text><Text style={styles.body}>بيانات حسابك محفوظة في الخدمة السحابية. جرّب إعادة فتح الواجهة، وإن استمر الخطأ أغلق التطبيق وافتحه مجددًا.</Text><Pressable accessibilityRole="button" accessibilityLabel="إعادة فتح واجهة عتيك" onPress={this.reset} style={styles.button}><Text style={styles.buttonText}>إعادة فتح الواجهة</Text></Pressable><Text style={styles.footer}>الإصدار {BUILD_INFO.versionName} • البناء {BUILD_INFO.versionCode} • {BUILD_INFO.shortSha}</Text></View></SafeAreaView>}}
function Shell(){const{resolved,toggle,colors:c}=useAteekTheme();const[touch,setTouch]=useState({x:.5,y:.5});const scale=useRef(new Animated.Value(1)).current;const onTouch=(e:any)=>{const{locationX,locationY}=e.nativeEvent;const{width,height}=Dimensions.get('window');setTouch({x:Math.max(0,Math.min(1,locationX/width)),y:Math.max(0,Math.min(1,locationY/height))})};const tap=()=>{Animated.sequence([Animated.spring(scale,{toValue:.88,useNativeDriver:true,speed:40,bounciness:4}),Animated.spring(scale,{toValue:1,useNativeDriver:true,speed:30,bounciness:8})]).start();toggle()};return <View style={[styles.shell,{backgroundColor:c.cream}]} onTouchStart={onTouch} onTouchMove={onTouch}><DynamicBackground touchX={touch.x} touchY={touch.y}/><OnlineApp/><Animated.View style={[styles.themeFloat,{transform:[{scale}],backgroundColor:c.glassStrong,borderColor:c.line}]}><Pressable accessibilityRole="button" accessibilityLabel={resolved==='dark'?'تفعيل الوضع الفاتح':'تفعيل الوضع الداكن'} onPress={tap} hitSlop={8} style={styles.themePress}><Ionicons name={resolved==='dark'?'sunny':'moon'} size={18} color={c.gold}/></Pressable></Animated.View><View pointerEvents="none" accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={[styles.buildBadge,{backgroundColor:resolved==='dark'?'rgba(4,16,12,.92)':'rgba(255,255,255,.92)',borderColor:c.gold}]}><Text style={[styles.buildBadgeText,{color:c.gold}]}>ATEEK {BUILD_INFO.versionName} • #{BUILD_INFO.versionCode} • {BUILD_INFO.shortSha}</Text></View></View>}
export default function AppShell(){return <AppErrorBoundary><ThemeProvider><Shell/></ThemeProvider></AppErrorBoundary>}
const styles=StyleSheet.create({shell:{flex:1},root:{flex:1,backgroundColor:colors.forest,justifyContent:'center',padding:20},card:{backgroundColor:colors.glassStrong,borderRadius:26,padding:22,gap:14,borderWidth:1,borderColor:colors.line},brand:{color:colors.gold,fontWeight:'900',textAlign:'right',fontSize:16},title:{color:colors.ink,fontWeight:'900',textAlign:'right',fontSize:22},body:{color:colors.ink,textAlign:'right',lineHeight:24,fontSize:14},button:{minHeight:50,backgroundColor:colors.gold,borderRadius:16,alignItems:'center',justifyContent:'center'},buttonText:{color:colors.forest,fontWeight:'900'},footer:{color:colors.muted,textAlign:'center',fontSize:10,marginTop:4},buildBadge:{position:'absolute',left:8,bottom:3,borderRadius:7,paddingHorizontal:7,paddingVertical:3,borderWidth:1},buildBadgeText:{fontSize:9,fontWeight:'800'},themeFloat:{position:'absolute',right:12,top:46,width:42,height:42,borderRadius:21,borderWidth:1,overflow:'hidden',elevation:8},themePress:{flex:1,alignItems:'center',justifyContent:'center'}});
