import React,{useRef,useState} from 'react';
import { Animated,Dimensions,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,StyleSheet,Text,View,useWindowDimensions } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import OnlineApp from './cloud/OnlineApp';
import { DynamicBackground } from './components/DynamicBackground';
import { AICapsule } from './components/AICapsule';
import { SpatialSocialHub } from './social/SpatialSocialHub';
import { colors } from './theme/colors';
import { ThemeProvider,useAteekTheme } from './theme/ThemeProvider';
import { haptics } from './system/haptics';
import { BUILD_INFO } from './config/buildInfo';
type State={failed:boolean};
class AppErrorBoundary extends React.Component<React.PropsWithChildren,State>{state:State={failed:false};static getDerivedStateFromError():State{return{failed:true}}componentDidCatch(error:unknown){console.error('ATEEK UI error',error)}reset=()=>this.setState({failed:false});render(){if(!this.state.failed)return this.props.children;return <SafeAreaView style={styles.root}><View style={styles.card}><Text style={styles.brand}>ATEEK • عتيك</Text><Text style={styles.title}>حدث خطأ غير متوقع في الواجهة</Text><Text style={styles.body}>بيانات حسابك محفوظة في الخدمة السحابية. جرّب إعادة فتح الواجهة.</Text><Pressable accessibilityRole="button" onPress={this.reset} style={styles.button}><Text style={styles.buttonText}>إعادة فتح الواجهة</Text></Pressable><Text style={styles.footer}>ATEEK {BUILD_INFO.versionName} Spatial Social • #{BUILD_INFO.versionCode} • {BUILD_INFO.shortSha}</Text></View></SafeAreaView>}}
function Shell(){const{height}=useWindowDimensions();const{resolved,toggle,colors:c,lowData,setLowData,isRTL,t}=useAteekTheme();const[touch,setTouch]=useState({x:.5,y:.5});const scale=useRef(new Animated.Value(1)).current;const gesture=useRef({x:0,y:0,moved:false,at:0});const point=(e:any)=>{const{locationX,locationY}=e.nativeEvent;const{width,height:h}=Dimensions.get('window');return{x:locationX,y:locationY,nx:Math.max(0,Math.min(1,locationX/width)),ny:Math.max(0,Math.min(1,locationY/h))}};const onTouchStart=(e:any)=>{const p=point(e);gesture.current={x:p.x,y:p.y,moved:false,at:Date.now()};setTouch({x:p.nx,y:p.ny})};const onTouchMove=(e:any)=>{const p=point(e);if(Math.hypot(p.x-gesture.current.x,p.y-gesture.current.y)>12)gesture.current.moved=true;setTouch({x:p.nx,y:p.ny})};const onTouchEnd=()=>{if(!gesture.current.moved&&Date.now()-gesture.current.at<700)haptics.tap()};const tap=()=>{haptics.medium();Animated.sequence([Animated.spring(scale,{toValue:.88,useNativeDriver:true,speed:40,bounciness:4}),Animated.spring(scale,{toValue:1,useNativeDriver:true,speed:30,bounciness:8})]).start();toggle()};const kOffset=Math.max(12,Math.min(40,Math.round(height*.025)));return <View style={[styles.shell,{backgroundColor:c.cream,direction:isRTL?'rtl':'ltr'}]} onTouchStart={onTouchStart} onTouchMove={onTouchMove} onTouchEnd={onTouchEnd}><DynamicBackground touchX={touch.x} touchY={touch.y}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':'height'} keyboardVerticalOffset={kOffset}><OnlineApp/></KeyboardAvoidingView><AICapsule/><SpatialSocialHub/><Animated.View style={[styles.themeFloat,{transform:[{scale}],backgroundColor:c.glassStrong,borderColor:c.line}]}><Pressable onPress={tap} style={styles.themePress}><Ionicons name={resolved==='dark'?'sunny':'moon'} size={24} color={c.gold}/></Pressable></Animated.View><View style={[styles.dataFloat,{backgroundColor:c.glassStrong,borderColor:lowData?c.cyan:c.line}]}><Pressable onPress={()=>{haptics.light();setLowData(!lowData)}} style={styles.themePress}><Ionicons name={lowData?'speedometer':'speedometer-outline'} size={24} color={lowData?c.cyan:c.muted}/></Pressable></View><View pointerEvents="none" style={[styles.buildBadge,{backgroundColor:resolved==='dark'?'rgba(9,10,15,.96)':'rgba(255,255,255,.96)',borderColor:c.gold}]}><Text style={[styles.buildBadgeText,{color:c.gold}]}>ATEEK {BUILD_INFO.versionName} Spatial Social • #{BUILD_INFO.versionCode} • {BUILD_INFO.shortSha}</Text></View></View>}
export default function AppShell(){return <AppErrorBoundary><ThemeProvider><Shell/></ThemeProvider></AppErrorBoundary>}
const styles=StyleSheet.create({shell:{flex:1},root:{flex:1,backgroundColor:colors.forest,justifyContent:'center',padding:20},card:{backgroundColor:colors.glassStrong,borderRadius:26,padding:22,gap:14,borderWidth:1,borderColor:colors.line},brand:{color:colors.gold,fontWeight:'900',textAlign:'right',fontSize:16},title:{color:colors.ink,fontWeight:'900',textAlign:'right',fontSize:22},body:{color:colors.ink,textAlign:'right',lineHeight:24,fontSize:14},button:{minHeight:50,backgroundColor:colors.gold,borderRadius:16,alignItems:'center',justifyContent:'center'},buttonText:{color:colors.forest,fontWeight:'900'},footer:{color:colors.muted,textAlign:'center',fontSize:10,marginTop:4},buildBadge:{position:'absolute',left:8,bottom:3,borderRadius:7,paddingHorizontal:7,paddingVertical:3,borderWidth:1},buildBadgeText:{fontSize:9,fontWeight:'800'},themeFloat:{position:'absolute',right:12,top:46,width:44,height:44,borderRadius:15,borderWidth:1,overflow:'hidden',elevation:8},dataFloat:{position:'absolute',right:12,top:96,width:44,height:44,borderRadius:15,borderWidth:1,overflow:'hidden',elevation:8},themePress:{flex:1,alignItems:'center',justifyContent:'center'}});
