-- Run #76 additive production migration. Existing Auth and existing RLS policies are untouched.
alter table public.ateek_profiles add column if not exists analytics_cache jsonb not null default '{}'::jsonb;
alter table public.ateek_profiles add column if not exists stream_quality text not null default 'auto' check (stream_quality in ('auto','720p','1080p'));
alter table public.ateek_profiles add column if not exists listing_sort text not null default 'newest' check (listing_sort in ('newest','nearest','most_viewed'));
alter table public.ateek_profiles add column if not exists animations_enabled boolean not null default true;
alter table public.ateek_profiles add column if not exists activity_visible boolean not null default true;
alter table public.ateek_profiles add column if not exists comment_permission text not null default 'all' check (comment_permission in ('all','followers','none'));
create table if not exists public.ateek_deletion_requests(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,requested_at timestamptz not null default now(),delete_after timestamptz not null default(now()+interval '30 days'),status text not null default 'pending' check(status in('pending','cancelled','processed')),processed_at timestamptz);
alter table public.ateek_deletion_requests enable row level security;
revoke all on public.ateek_deletion_requests from anon,authenticated;
create or replace function public.ateek_profile_preferences_update(p_stream_quality text,p_listing_sort text,p_animations_enabled boolean,p_activity_visible boolean,p_comment_permission text) returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); begin if uid is null then raise exception 'AUTH_REQUIRED'; end if; if p_stream_quality not in('auto','720p','1080p') then raise exception 'INVALID_STREAM_QUALITY'; end if; if p_listing_sort not in('newest','nearest','most_viewed') then raise exception 'INVALID_LISTING_SORT'; end if; if p_comment_permission not in('all','followers','none') then raise exception 'INVALID_COMMENT_PERMISSION'; end if; update public.ateek_profiles set stream_quality=p_stream_quality,listing_sort=p_listing_sort,animations_enabled=coalesce(p_animations_enabled,true),activity_visible=coalesce(p_activity_visible,true),comment_permission=p_comment_permission where id=uid; return jsonb_build_object('ok',true); end $$;
revoke all on function public.ateek_profile_preferences_update(text,text,boolean,boolean,text) from public; grant execute on function public.ateek_profile_preferences_update(text,text,boolean,boolean,text) to authenticated;
create or replace function public.ateek_delete_account_request() returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid(); d timestamptz; begin if uid is null then raise exception 'AUTH_REQUIRED'; end if; d:=now()+interval '30 days'; insert into public.ateek_deletion_requests(user_id,requested_at,delete_after,status) values(uid,now(),d,'pending') on conflict(user_id) do update set requested_at=excluded.requested_at,delete_after=excluded.delete_after,status='pending',processed_at=null; return jsonb_build_object('ok',true,'delete_after',d,'mode','scheduled_request'); end $$;
revoke all on function public.ateek_delete_account_request() from public; grant execute on function public.ateek_delete_account_request() to authenticated;
create or replace function public.ateek_refresh_all_analytics_cache() returns integer language plpgsql security definer set search_path=public as $$ declare r record; updated_count integer:=0; f bigint; pv bigint; lv bigint; begin for r in select id from public.ateek_profiles loop select count(*) into f from public.ateek_follows where followed_id=r.id; select count(*) into pv from public.ateek_profile_views where profile_id=r.id and viewed_at>=now()-interval '30 days'; select coalesce(sum(case when views_date=current_date then views_today else 0 end),0) into lv from public.ateek_listings where seller_id=r.id; update public.ateek_profiles set analytics_cache=jsonb_build_object('followers_count',f,'profile_views_30d',pv,'listing_views_today',lv,'views_30d',null,'engagement_rate',null,'generated_at',now(),'coverage','followers/profile_views_30d/listing_views_today; ad_views+likes unavailable') where id=r.id; updated_count:=updated_count+1; end loop; return updated_count; end $$;
revoke all on function public.ateek_refresh_all_analytics_cache() from public,anon,authenticated; grant execute on function public.ateek_refresh_all_analytics_cache() to service_role;
